# Generated by Django 5.2.7 on 2025-10-28 06:58

import datetime
import django.core.validators
import django.db.models.deletion
import facial_auth.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('access_level', models.IntegerField(default=1, help_text='1=Lowest, 5=Highest security', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Security Area',
                'verbose_name_plural': 'Security Areas',
                'ordering': ['access_level'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_level',
            field=models.IntegerField(default=1, help_text='Maximum security level this user can access', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pass_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 27, 6, 57, 15, 579140, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pass_issued',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 27, 6, 58, 30, 487119, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pass_photo',
            field=models.ImageField(blank=True, null=True, upload_to=facial_auth.models.pass_photo_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'System Administrator'), ('security', 'Security Officer'), ('staff', 'Regular Staff'), ('visitor', 'Temporary Visitor'), ('contractor', 'Contractor')], default='staff', max_length=20),
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_granted', models.BooleanField(default=False)),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('access_point', models.CharField(blank=True, max_length=100)),
                ('reason_denied', models.TextField(blank=True)),
                ('authentication_method', models.CharField(choices=[('face', 'Facial Recognition'), ('security_number', 'Security Number'), ('both', 'Both Methods')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('security_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facial_auth.securityarea')),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'ordering': ['-access_time'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allowed_areas',
            field=models.ManyToManyField(blank=True, to='facial_auth.securityarea'),
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.TextField()),
                ('hosting_staff', models.CharField(blank=True, max_length=100)),
                ('areas_visited', models.ManyToManyField(blank=True, to='facial_auth.securityarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitor Log',
                'verbose_name_plural': 'Visitor Logs',
                'ordering': ['-entry_time'],
            },
        ),
        migrations.DeleteModel(
            name='AuthenticationLog',
        ),
    ]
