# Generated by Django 5.2.7 on 2025-10-30 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_auth', '0003_alter_userprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pass_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 29, 13, 33, 32, 174786, tzinfo=datetime.timezone.utc)),
        ),
    ]
