# Generated by Django 5.2.7 on 2025-10-31 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_auth', '0004_alter_userprofile_pass_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pass_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 13, 14, 56, 547813, tzinfo=datetime.timezone.utc)),
        ),
    ]
