# Generated by Django 5.2.7 on 2025-11-01 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_auth', '0005_alter_userprofile_pass_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pass_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 18, 46, 43, 146639, tzinfo=datetime.timezone.utc)),
        ),
    ]
